### ISSUE TITLE
How to cite this work

### ISSUE THREAD

**Issue by pbpf** [jonnyhyman/Convex_Symbolic#12]
Hello there,
I try to cite Convex_Symbolic in my paper, in follow way

@manual{Convex_Symbolic ,
   author = "Jonny Hyman",
   title = "Python symbolic canonicalizer and C code generator for embedding convex optimization problems",
   year = 2018,
   url = "https://github.com/jonnyhyman/Convex_Symbolic"
 }

Is this ok?

**Comment by jonnyhyman** [comment]
Perfect for me, thank you!
